"""empty message

Revision ID: 107a05f9e896
Revises: 
Create Date: 2020-02-23 16:50:49.020273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107a05f9e896'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('price', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=85), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('Prices')
    # ### end Alembic commands ###
